### ISSUE TITLE
bug: Some global icons are not readable

### ISSUE THREAD

**Issue by Kallecrafter** [Global-Tags/LabyAddon#84] opened 2024-12-09 13:44 UTC
### Describe the bug

Some global icons are not readable
![image](https://github.com/user-attachments/assets/0deadf28-1be0-415d-bf56-f59aeabf6f72)

### To Reproduce

I have no idea what is going on here.

### Expected behavior

Es sollten alle Angezeigt werden

### Actual behavior

If you want to select global icons, only a few global icons are actually displayed, not the icons themselves, but the names of the icons in the menu. The following icons are readable:
None,
Custom,
Crown, 
Heart,
star,
Telegram.
Nothing more.

### Version

1.3.6

**Comment by RappyTV** [comment] 2024-12-09 14:06
Does this issue also occur in vanilla theme?

**Comment by Kallecrafter** [comment] 2024-12-09 15:19
![image](https://github.com/user-attachments/assets/33d58aa8-3bbd-4fc0-8eaf-9dbcf236b3b7)

**Comment by RappyTV** [comment] 2024-12-09 15:28
Alright, we identified your issue. Please be patient until it's fixed.

**Comment by RappyTV** [comment] 2024-12-10 19:06
The issue is fixed now but won't be released yet. Please wait for the next major update for the fix... Thanks for the issue and your patience!

**Closed as completed by RappyTV** 2024-12-10 19:06 UTC
Labels: bug

**Comment by RappyTV** [comment] 2025-01-16 16:10
The release containing the fix just got released so the issue should be fixed now
